export interface Question {
  id: string;
  category: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

export interface Flashcard {
  id: string;
  category: string;
  front: string;
  back: string;
}

export const CATEGORIES = {
  FUNDAMENTALS: "Security Fundamentals",
  THREATS: "Cyber Threats and Vulnerabilities",
  DESIGN: "Security and Design",
  NETWORK: "Network and Data Security",
  OPERATIONS: "Security Operations and Management",
  MITIGATION: "Security Protocols and Threat Mitigation",
};

export const STUDY_DATA: { questions: Question[]; flashcards: Flashcard[] } = {
  questions: [
    // ── Security Fundamentals ──
    {
      id: "f1",
      category: CATEGORIES.FUNDAMENTALS,
      question: "A database administrator discovers that employee records were modified without any authorized change request. Which pillar of the CIA triad has been MOST directly violated?",
      options: ["Confidentiality", "Availability", "Integrity", "Authentication"],
      correctAnswer: 2,
      explanation: "Integrity ensures data is not altered by unauthorized parties. Unauthorized record changes are a direct integrity violation. Confidentiality covers unauthorized access, not modification.",
    },
    {
      id: "f2",
      category: CATEGORIES.FUNDAMENTALS,
      question: "A help desk technician requires the ability to reset user passwords but should NOT have access to financial reports. Which of the following security principles BEST describes this configuration?",
      options: ["Separation of duties", "Least privilege", "Zero Trust", "Need to know"],
      correctAnswer: 1,
      explanation: "Least privilege grants users only the minimum permissions required for their specific role. Separation of duties requires multiple people to complete a sensitive task — a related but distinct concept.",
    },
    {
      id: "f3",
      category: CATEGORIES.FUNDAMENTALS,
      question: "A SIEM generates a log entry each time a user accesses a sensitive file. Which component of the AAA framework does this BEST represent?",
      options: ["Authentication", "Authorization", "Accounting", "Access control"],
      correctAnswer: 2,
      explanation: "Accounting (auditing) tracks and records what authenticated, authorized users do on a system. Authentication verifies identity; authorization determines what they can do.",
    },
    {
      id: "f4",
      category: CATEGORIES.FUNDAMENTALS,
      question: "A security engineer deploys a realistic but fake server on the network to observe attacker behavior after a breach is detected. Which of the following BEST describes this device?",
      options: ["Sandbox", "Honeyfile", "Honeypot", "DMZ"],
      correctAnswer: 2,
      explanation: "A honeypot is a decoy system designed to lure attackers so their techniques can be studied. A honeyfile is a fake file, not a server. A sandbox is used for safe malware analysis.",
    },
    {
      id: "f5",
      category: CATEGORIES.FUNDAMENTALS,
      question: "After a wire transfer is processed, a bank employee denies having authorized it. Which of the following security properties, if implemented, would BEST prevent this denial?",
      options: ["Integrity", "Confidentiality", "Non-repudiation", "Availability"],
      correctAnswer: 2,
      explanation: "Non-repudiation, typically implemented via digital signatures, provides cryptographic proof that a specific party performed an action and cannot later deny it.",
    },
    {
      id: "f6",
      category: CATEGORIES.FUNDAMENTALS,
      question: "A user is required to insert a smart card into a reader before accessing a workstation. Which of the following authentication factor categories does the smart card represent?",
      options: ["Something you know", "Something you are", "Something you have", "Somewhere you are"],
      correctAnswer: 2,
      explanation: "A smart card is a physical possession of the user — it falls under 'something you have.' A password is 'something you know'; a fingerprint is 'something you are.'",
    },
    {
      id: "f7",
      category: CATEGORIES.FUNDAMENTALS,
      question: "A memory address is displayed as 0x1A3F in a debugger. Which of the following number systems is being used?",
      options: ["Binary", "Octal", "Decimal", "Hexadecimal"],
      correctAnswer: 3,
      explanation: "The '0x' prefix is the standard notation for hexadecimal (base 16), which uses digits 0–9 and letters A–F. Binary uses only 0 and 1; octal uses digits 0–7.",
    },
    {
      id: "f8",
      category: CATEGORIES.FUNDAMENTALS,
      question: "During a secure boot process, the firmware cryptographically measures and verifies the OS loader before allowing it to execute. Which of the following terms BEST describes this process?",
      options: ["Identity proofing", "Accounting", "Attestation", "Authorization"],
      correctAnswer: 2,
      explanation: "Attestation provides cryptographic proof that a system's hardware and software are in a known, trusted state. Identity proofing verifies a person's real-world identity, not a system's state.",
    },
    {
      id: "f9",
      category: CATEGORIES.FUNDAMENTALS,
      question: "A company implements a policy requiring that every access request be explicitly verified, regardless of whether the user is already on the internal network. Which of the following security models does this BEST represent?",
      options: ["Defense in depth", "Zero Trust", "Implicit trust", "Perimeter security"],
      correctAnswer: 1,
      explanation: "Zero Trust operates on 'never trust, always verify.' Unlike perimeter security, it does not grant implicit trust to users or devices inside the network boundary.",
    },
    {
      id: "f10",
      category: CATEGORIES.FUNDAMENTALS,
      question: "A security team deploys a collection of interconnected decoy servers, workstations, and routers that simulate an entire production environment. Which of the following terms BEST describes this setup?",
      options: ["Sandbox", "Honeypot", "DMZ", "Honeynet"],
      correctAnswer: 3,
      explanation: "A honeynet is a network of multiple honeypots mimicking a real production environment. A single honeypot is one decoy system; a honeynet is a full decoy network.",
    },
    {
      id: "f11",
      category: CATEGORIES.FUNDAMENTALS,
      question: "Which of the following is the CORRECT decimal equivalent of the binary number 11001010?",
      options: ["192", "194", "202", "212"],
      correctAnswer: 2,
      explanation: "11001010 = 128 + 64 + 0 + 0 + 8 + 0 + 2 + 0 = 202.",
    },
    {
      id: "f12",
      category: CATEGORIES.FUNDAMENTALS,
      question: "Before issuing credentials to a new employee, the IT department requires the employee to appear in person with a government-issued ID. Which of the following processes does this BEST describe?",
      options: ["Attestation", "Authorization", "Identity proofing", "Non-repudiation"],
      correctAnswer: 2,
      explanation: "Identity proofing verifies a person's real-world identity before credentials or certificates are issued. Attestation is used to verify a system's trusted state, not a person's identity.",
    },
    {
      id: "f13",
      category: CATEGORIES.FUNDAMENTALS,
      question: "Which of the following is the CORRECT decimal equivalent of the hexadecimal value 0xFF?",
      options: ["128", "200", "255", "256"],
      correctAnswer: 2,
      explanation: "0xFF = (15 × 16) + 15 = 240 + 15 = 255. This is also the maximum value for a single byte.",
    },
    {
      id: "f14",
      category: CATEGORIES.FUNDAMENTALS,
      question: "An analyst places a file named 'CEO_Salary_2026.xlsx' on a shared network drive. The file contains no real data, but opening it triggers a security alert. Which of the following BEST describes this technique?",
      options: ["Honeypot", "Sandbox file", "Honeyfile", "Canary token"],
      correctAnswer: 2,
      explanation: "A honeyfile is a decoy file designed to look valuable. Accessing it triggers an alert, revealing unauthorized access. A honeypot is an entire system, not a single file.",
    },

    // ── Cyber Threats and Vulnerabilities ──
    {
      id: "t1",
      category: CATEGORIES.THREATS,
      question: "An attacker exploits a critical flaw in a VPN application before the vendor is even aware the flaw exists. Which of the following BEST describes this type of vulnerability?",
      options: ["Backdoor", "Unpatched CVE", "Zero-day", "Logic bomb"],
      correctAnswer: 2,
      explanation: "A zero-day vulnerability is unknown to the vendor — there are 'zero days' of warning and no patch exists at the time of exploitation. An unpatched CVE is a known vulnerability with an available but unapplied fix.",
    },
    {
      id: "t2",
      category: CATEGORIES.THREATS,
      question: "Malware propagates itself to every machine on a network by exploiting an SMB vulnerability, requiring no interaction from any user. Which of the following malware types BEST describes this behavior?",
      options: ["Trojan", "Virus", "Ransomware", "Worm"],
      correctAnswer: 3,
      explanation: "Worms self-replicate across networks without human interaction. A virus requires a user to execute an infected file to spread. A Trojan disguises itself as legitimate software but does not self-replicate.",
    },
    {
      id: "t3",
      category: CATEGORIES.THREATS,
      question: "A web server becomes unreachable after thousands of compromised IoT devices simultaneously flood it with requests. Which of the following attack types BEST describes what is occurring?",
      options: ["SQL injection", "Man-in-the-middle", "DDoS", "Replay attack"],
      correctAnswer: 2,
      explanation: "A Distributed Denial of Service (DDoS) attack uses many compromised hosts to overwhelm a target, exhausting its resources. A DoS attack comes from a single source; DDoS uses many.",
    },
    {
      id: "t4",
      category: CATEGORIES.THREATS,
      question: "A user receives an email appearing to be from a financial institution requesting account verification via an embedded link. The link directs to a fake login page. Which of the following attack types does this BEST represent?",
      options: ["Vishing", "Smishing", "Phishing", "Pharming"],
      correctAnswer: 2,
      explanation: "Phishing uses fraudulent emails impersonating trusted entities to steal credentials or install malware. Vishing uses voice/phone calls; smishing uses SMS text messages.",
    },
    {
      id: "t5",
      category: CATEGORIES.THREATS,
      question: "A cryptanalyst discovers that two different input files produce the same MD5 hash value. Which of the following attacks does this BEST illustrate?",
      options: ["Replay attack", "Birthday attack", "Downgrade attack", "Brute force"],
      correctAnswer: 1,
      explanation: "A birthday attack exploits the birthday paradox to find two inputs that hash to the same value (a collision). A brute force attack tries all possible inputs to find a match to a specific hash.",
    },
    {
      id: "t6",
      category: CATEGORIES.THREATS,
      question: "An unauthorized individual gains access to a secure facility by walking closely behind a badge-carrying employee as they enter through a secured door. Which of the following BEST describes this technique?",
      options: ["Shoulder surfing", "Dumpster diving", "Piggybacking", "Vishing"],
      correctAnswer: 2,
      explanation: "Piggybacking (tailgating) is a physical security attack where an unauthorized person follows an authorized person through a secured entry point without using their own credentials.",
    },
    {
      id: "t7",
      category: CATEGORIES.THREATS,
      question: "A technician detects a rogue Wi-Fi access point broadcasting the same SSID as the corporate guest network. Client devices are connecting to it instead of the legitimate AP. Which of the following attack types does this BEST represent?",
      options: ["War driving", "Bluejacking", "Evil twin", "Deauthentication attack"],
      correctAnswer: 2,
      explanation: "An evil twin attack creates a fraudulent AP with the same SSID as a legitimate network to intercept client traffic. A deauthentication attack disconnects clients from a network but doesn't redirect them.",
    },
    {
      id: "t8",
      category: CATEGORIES.THREATS,
      question: "Malware on a compromised server intercepts administrator commands while hiding its own processes from the OS task manager. Which of the following malware types BEST describes this behavior?",
      options: ["Spyware", "Keylogger", "Adware", "Rootkit"],
      correctAnswer: 3,
      explanation: "A rootkit hides itself and other malware from the OS while providing persistent, elevated access to the attacker. A keylogger records keystrokes but does not typically hide system processes.",
    },
    {
      id: "t9",
      category: CATEGORIES.THREATS,
      question: "A developer embeds code that will delete all payroll records if their username is ever removed from the system. The code has not yet executed. Which of the following BEST describes this threat?",
      options: ["Ransomware", "Logic bomb", "Trojan", "Worm"],
      correctAnswer: 1,
      explanation: "A logic bomb is dormant code that executes when a specific trigger condition is met — such as a user deletion or a date. It differs from ransomware, which activates immediately upon execution.",
    },
    {
      id: "t10",
      category: CATEGORIES.THREATS,
      question: "An attacker sends 10,000 bytes of data to an input field that expects only 100 bytes, causing the application to crash and execute arbitrary code. Which of the following vulnerabilities was exploited?",
      options: ["SQL injection", "Integer overflow", "Buffer overflow", "Race condition"],
      correctAnswer: 2,
      explanation: "A buffer overflow occurs when more data is written to a memory buffer than it can hold, overwriting adjacent memory. This can allow attackers to redirect execution to malicious code.",
    },
    {
      id: "t11",
      category: CATEGORIES.THREATS,
      question: "An attacker sends a highly targeted email to a company's CFO referencing their name, recent acquisition activity, and the CFO's executive assistant by name. Which of the following attack types BEST describes this?",
      options: ["Spear phishing", "Vishing", "Smishing", "Whaling"],
      correctAnswer: 3,
      explanation: "Whaling is a spear phishing attack that specifically targets C-suite executives or other high-value individuals. Spear phishing is targeted but not necessarily aimed at executives.",
    },
    {
      id: "t12",
      category: CATEGORIES.THREATS,
      question: "A login form passes user input directly into a database query without sanitization. An attacker enters ' OR '1'='1 and gains access without valid credentials. Which of the following attacks occurred?",
      options: ["XSS", "CSRF", "SQL injection", "Directory traversal"],
      correctAnswer: 2,
      explanation: "SQL injection inserts malicious SQL code into unsanitized input fields, manipulating the underlying database query. In this case, the condition '1'='1' always evaluates to true, bypassing authentication.",
    },
    {
      id: "t13",
      category: CATEGORIES.THREATS,
      question: "Two threads in an application both read a user's account balance before either completes a withdrawal. Both see sufficient funds and both execute, resulting in a negative balance. Which of the following BEST describes this vulnerability?",
      options: ["Buffer overflow", "Integer overflow", "Race condition", "Logic bomb"],
      correctAnswer: 2,
      explanation: "A race condition occurs when system behavior depends on the timing of events. The gap between the balance check and the transaction (check-then-act) is exploited to allow two simultaneous withdrawals.",
    },
    {
      id: "t14",
      category: CATEGORIES.THREATS,
      question: "An attacker intercepts a TLS 1.3 handshake and manipulates both endpoints into negotiating SSLv3 instead. Which of the following attacks BEST describes this technique?",
      options: ["Replay attack", "Birthday attack", "Downgrade attack", "Session hijacking"],
      correctAnswer: 2,
      explanation: "A downgrade attack forces communicating parties to use an older, weaker protocol version with known vulnerabilities. A replay attack reuses captured authentication tokens, not protocol negotiation.",
    },
    {
      id: "t15",
      category: CATEGORIES.THREATS,
      question: "An attacker researches a target on LinkedIn and sends an email referencing the target's current project and a colleague by name to appear legitimate. Which of the following BEST describes this technique?",
      options: ["Whaling", "Vishing", "Smishing", "Spear phishing"],
      correctAnswer: 3,
      explanation: "Spear phishing uses personally gathered information to craft a highly convincing, targeted attack. Whaling is a subset of spear phishing aimed specifically at executives.",
    },
    {
      id: "t16",
      category: CATEGORIES.THREATS,
      question: "A user downloads a free utility. Without their knowledge, the application records every keystroke and transmits the data to a remote server. Which of the following malware types is MOST likely running?",
      options: ["Ransomware", "Rootkit", "Keylogger", "Adware"],
      correctAnswer: 2,
      explanation: "A keylogger silently records all keystrokes to capture passwords and other sensitive input. Adware displays unwanted advertisements; ransomware encrypts files and demands payment.",
    },
    {
      id: "t17",
      category: CATEGORIES.THREATS,
      question: "An IoT thermostat uses Telnet with the factory default password 'admin:admin' and has not been updated since it shipped. An attacker takes remote control. Which of the following vulnerability categories BEST applies?",
      options: ["Zero-day", "Race condition", "Default credentials / unpatched firmware", "Buffer overflow"],
      correctAnswer: 2,
      explanation: "IoT devices frequently ship with default credentials and outdated firmware. Failure to change defaults and apply updates is one of the most common IoT attack vectors.",
    },
    {
      id: "t18",
      category: CATEGORIES.THREATS,
      question: "A user installs a program advertised as a free antivirus tool. After installation, the program opens a backdoor on the system and connects to an attacker's server. Which of the following malware types BEST describes this?",
      options: ["Worm", "Virus", "Trojan horse", "Rootkit"],
      correctAnswer: 2,
      explanation: "A Trojan horse masquerades as legitimate software but carries a malicious payload. Unlike a worm, it does not self-replicate. Unlike a virus, it does not attach itself to other files.",
    },
    {
      id: "t19",
      category: CATEGORIES.THREATS,
      question: "A virus requires a user to open an infected email attachment before it can execute and spread to other files. Which of the following BEST explains how this differs from a worm?",
      options: ["A virus uses encryption; a worm does not", "A virus requires user interaction to spread; a worm spreads automatically", "A virus only affects Windows systems; a worm is cross-platform", "There is no significant difference"],
      correctAnswer: 1,
      explanation: "Viruses require a user to execute an infected file to activate and spread. Worms self-propagate across networks without any human interaction by exploiting vulnerabilities.",
    },
    {
      id: "t20",
      category: CATEGORIES.THREATS,
      question: "An attacker captures a valid session token from network traffic and uses it to authenticate to a web application as that user. Which of the following BEST describes this attack?",
      options: ["Birthday attack", "Replay attack", "Downgrade attack", "SQL injection"],
      correctAnswer: 1,
      explanation: "A replay attack reuses captured authentication credentials or tokens to impersonate a legitimate user. It is mitigated by session expiration, nonces, and timestamped tokens.",
    },

    // ── Security and Design ──
    {
      id: "d1",
      category: CATEGORIES.DESIGN,
      question: "A company migrates its CRM application to a cloud provider that manages the OS, runtime, and middleware. The company only manages the application and its data. Which of the following cloud models BEST describes this arrangement?",
      options: ["IaaS", "SaaS", "FaaS", "PaaS"],
      correctAnswer: 3,
      explanation: "PaaS (Platform as a Service) — the provider manages the underlying platform (OS, runtime, database). The customer manages only the application and data. IaaS gives the customer OS-level control.",
    },
    {
      id: "d2",
      category: CATEGORIES.DESIGN,
      question: "A DevOps team packages each microservice with its dependencies into isolated, portable units that share the host OS kernel. Which of the following technologies are they MOST likely using?",
      options: ["Virtual machines", "Containers", "Type-1 hypervisor", "DMZ"],
      correctAnswer: 1,
      explanation: "Containers share the host OS kernel but provide isolated environments for each application. VMs require a full guest OS per instance, making them heavier than containers.",
    },
    {
      id: "d3",
      category: CATEGORIES.DESIGN,
      question: "A storage array has four drives configured so that each drive has an exact duplicate. If one drive fails, the array continues operating with no data loss. Which RAID level is configured?",
      options: ["RAID 0", "RAID 5", "RAID 1", "RAID 6"],
      correctAnswer: 2,
      explanation: "RAID 1 mirrors data identically across two or more drives. RAID 0 provides no redundancy (striping only). RAID 5 uses distributed parity — not full mirroring.",
    },
    {
      id: "d4",
      category: CATEGORIES.DESIGN,
      question: "A data center requires servers to remain operational for at least 15 minutes after a power failure to allow for a controlled shutdown. Which of the following devices BEST provides this capability?",
      options: ["PDU", "Surge protector", "Generator", "UPS"],
      correctAnswer: 3,
      explanation: "A UPS (Uninterruptible Power Supply) provides immediate battery backup power. A generator takes time to start and is used for longer outages, not immediate bridging.",
    },
    {
      id: "d5",
      category: CATEGORIES.DESIGN,
      question: "A network administrator separates the finance department's traffic from the rest of the organization using software configuration on existing switches, without adding new cabling. Which of the following methods was MOST likely used?",
      options: ["Physical segmentation", "Air gap", "VLAN", "DMZ"],
      correctAnswer: 2,
      explanation: "VLANs provide logical (software-based) segmentation, separating traffic on shared hardware without physical changes. An air gap requires physical separation with no electronic connection.",
    },
    {
      id: "d6",
      category: CATEGORIES.DESIGN,
      question: "A company needs MAXIMUM control over the OS, storage, and networking of its cloud-hosted infrastructure. Which of the following cloud service models BEST meets this requirement?",
      options: ["SaaS", "PaaS", "IaaS", "DaaS"],
      correctAnswer: 2,
      explanation: "IaaS (Infrastructure as a Service) gives the customer full control from the OS layer up. SaaS provides the least control; PaaS provides control over the application layer but not the OS.",
    },
    {
      id: "d7",
      category: CATEGORIES.DESIGN,
      question: "A hospital's MRI machines run on an embedded OS that has not received a security update in five years because the vendor no longer provides patches. Which of the following IoT security concerns does this BEST represent?",
      options: ["Default credentials", "Evil twin vulnerability", "Inability to patch / limited hardware", "Bluetooth eavesdropping"],
      correctAnswer: 2,
      explanation: "Many IoT and medical devices lack the hardware resources or ongoing vendor support for regular security patching, leaving known vulnerabilities permanently open.",
    },
    {
      id: "d8",
      category: CATEGORIES.DESIGN,
      question: "A classified government network has no wireless interfaces and no wired connections to any external network, including the internet. Which of the following BEST describes this security implementation?",
      options: ["VLAN segmentation", "DMZ", "Air gap", "Zero Trust perimeter"],
      correctAnswer: 2,
      explanation: "An air gap is the most extreme physical segmentation — there is no electronic path between the isolated network and any external system. A DMZ still connects to the internet via a firewall.",
    },
    {
      id: "d9",
      category: CATEGORIES.DESIGN,
      question: "A five-drive storage array stripes data across all drives and distributes parity information so that the failure of any single drive does not result in data loss. Which RAID level is configured?",
      options: ["RAID 0", "RAID 1", "RAID 5", "RAID 10"],
      correctAnswer: 2,
      explanation: "RAID 5 uses block-level striping with distributed parity. It requires a minimum of three drives and can survive a single drive failure. RAID 0 has no fault tolerance.",
    },
    {
      id: "d10",
      category: CATEGORIES.DESIGN,
      question: "A security analyst executes a malware sample inside an isolated virtual machine to observe its behavior without risk to production systems. Which of the following security concepts BEST describes this?",
      options: ["Containerization", "Sandboxing", "Logical segmentation", "Air gapping"],
      correctAnswer: 1,
      explanation: "Sandboxing isolates suspicious code in a controlled, monitored environment for safe behavioral analysis. Containerization isolates applications for deployment, not malware analysis.",
    },
    {
      id: "d11",
      category: CATEGORIES.DESIGN,
      question: "A web server is placed in a network zone that accepts internet traffic, while a firewall separates it from the internal corporate network. Which of the following terms BEST describes this network zone?",
      options: ["VLAN", "Intranet", "DMZ", "Air gap"],
      correctAnswer: 2,
      explanation: "A DMZ (Demilitarized Zone) exposes public-facing services to the internet while keeping them isolated from the internal network by a firewall. An air gap has no internet connectivity at all.",
    },
    {
      id: "d12",
      category: CATEGORIES.DESIGN,
      question: "An application is divided into an authentication service, a payment service, and an inventory service that communicate via APIs. Which of the following architectural styles does this BEST represent?",
      options: ["Monolithic", "Serverless", "Layered", "Microservices"],
      correctAnswer: 3,
      explanation: "Microservices architecture decomposes an application into small, independently deployable services. Each API endpoint is an additional potential attack surface compared to a monolithic design.",
    },
    {
      id: "d13",
      category: CATEGORIES.DESIGN,
      question: "An organization follows the 3-2-1 backup strategy. How many copies of the data should be stored offsite?",
      options: ["0", "1", "2", "3"],
      correctAnswer: 1,
      explanation: "The 3-2-1 rule requires: 3 total copies, on 2 different media types, with 1 copy stored offsite to protect against local disasters such as fire or flood.",
    },

    // ── Network and Data Security ──
    {
      id: "n1",
      category: CATEGORIES.NETWORK,
      question: "Two parties need to communicate securely but have never met to exchange a key. Which of the following cryptography types BEST solves this key distribution problem?",
      options: ["Symmetric encryption", "Hashing", "Asymmetric encryption", "Steganography"],
      correctAnswer: 2,
      explanation: "Asymmetric encryption uses a public/private key pair. Anyone can encrypt with the recipient's public key, but only the private key holder can decrypt. This eliminates the need for a pre-shared secret.",
    },
    {
      id: "n2",
      category: CATEGORIES.NETWORK,
      question: "A server storing an encrypted database has been powered off and is not actively processing or transmitting any data. Which of the following BEST describes the state of this data?",
      options: ["Data in transit", "Data in use", "Data in process", "Data at rest"],
      correctAnswer: 3,
      explanation: "Data at rest refers to data stored on a medium (HDD, SSD, tape) that is not actively being accessed or transmitted. Full-disk encryption (e.g., BitLocker) is the primary protection for this state.",
    },
    {
      id: "n3",
      category: CATEGORIES.NETWORK,
      question: "A classified system assigns labels to all files (e.g., Top Secret, Secret). Access decisions are made entirely by the OS based on label matching, and users cannot change the labels. Which access control model is in use?",
      options: ["DAC", "RBAC", "MAC", "ABAC"],
      correctAnswer: 2,
      explanation: "MAC (Mandatory Access Control) enforces access based on system-assigned labels. Users cannot override or modify access controls — the OS makes all decisions. This is common in government and military environments.",
    },
    {
      id: "n4",
      category: CATEGORIES.NETWORK,
      question: "A browser displays a padlock and shows the website's verified name in the address bar after checking a document issued by a trusted third party. Which of the following BEST describes that document?",
      options: ["Private key", "Digital certificate", "Hash digest", "Session token"],
      correctAnswer: 1,
      explanation: "A digital certificate, signed by a Certificate Authority (CA), binds a public key to a verified identity. Browsers use it to confirm they are communicating with the legitimate site.",
    },
    {
      id: "n5",
      category: CATEGORIES.NETWORK,
      question: "A financial platform records every transaction in a chain where each entry contains a hash of the previous entry. Any tampering with a record would invalidate all subsequent entries. Which of the following technologies does this BEST describe?",
      options: ["RAID array", "PKI", "Blockchain", "SIEM"],
      correctAnswer: 2,
      explanation: "Blockchain is an immutable, distributed ledger where each block's hash is included in the next block. Any retroactive alteration changes the hash and breaks the chain, making tampering detectable.",
    },
    {
      id: "n6",
      category: CATEGORIES.NETWORK,
      question: "A cipher shifts each letter in the plaintext forward 13 positions in the alphabet so that A becomes N and B becomes O. Which of the following BEST describes this type of cipher?",
      options: ["Transposition cipher", "Asymmetric cipher", "Substitution (shift) cipher", "Block cipher"],
      correctAnswer: 2,
      explanation: "ROT13 is a Caesar cipher with a shift of 13 — a classic example of a substitution cipher. A transposition cipher rearranges the positions of characters rather than replacing them.",
    },
    {
      id: "n7",
      category: CATEGORIES.NETWORK,
      question: "Using a Caesar cipher with a shift of 3, what is the CORRECT encrypted output for the letter 'Z'?",
      options: ["A", "B", "C", "Y"],
      correctAnswer: 2,
      explanation: "With a shift of 3, the alphabet wraps around: X→A, Y→B, Z→C. Caesar ciphers always wrap from the end of the alphabet back to the beginning.",
    },
    {
      id: "n8",
      category: CATEGORIES.NETWORK,
      question: "After downloading a software package, a technician calculates the SHA-256 value and compares it to the value published by the vendor. Which of the following security properties is being verified?",
      options: ["Confidentiality", "Availability", "Authentication", "Integrity"],
      correctAnswer: 3,
      explanation: "Comparing hash values verifies integrity — any tampering with the file produces a different hash, immediately revealing the modification.",
    },
    {
      id: "n9",
      category: CATEGORIES.NETWORK,
      question: "A file server owner personally decides which coworkers can access specific shared folders, without any IT enforcement of those decisions. Which of the following access control models is in use?",
      options: ["MAC", "RBAC", "ABAC", "DAC"],
      correctAnswer: 3,
      explanation: "DAC (Discretionary Access Control) allows the resource owner to decide who has access at their own discretion. In MAC, the OS makes all access decisions; in RBAC, access is based on role.",
    },
    {
      id: "n10",
      category: CATEGORIES.NETWORK,
      question: "A VPN client prompts a user for their password and then sends a push notification to their registered mobile device for a second approval before granting access. Which of the following BEST describes this mechanism?",
      options: ["Single sign-on (SSO)", "Multi-factor authentication (MFA)", "Certificate-based authentication", "RBAC"],
      correctAnswer: 1,
      explanation: "MFA requires two or more independent verification factors: something you know (password) and something you have (phone with push app). SSO allows one login to access multiple systems — a different concept.",
    },
    {
      id: "n11",
      category: CATEGORIES.NETWORK,
      question: "A sender encrypts a hash of their message using their private key and appends the result to the message. The recipient decrypts it using the sender's public key to verify authenticity. Which of the following was created?",
      options: ["Session key", "Digital signature", "Symmetric key", "Certificate signing request"],
      correctAnswer: 1,
      explanation: "Encrypting a hash with a private key creates a digital signature. It proves the message came from the claimed sender (authentication) and that it was not altered (integrity), and enables non-repudiation.",
    },
    {
      id: "n12",
      category: CATEGORIES.NETWORK,
      question: "An employee's workstation is actively decrypting and displaying a video stream in a web conference. The video data currently loaded in RAM is in which of the following states?",
      options: ["Data at rest", "Data in transit", "Data in archive", "Data in use"],
      correctAnswer: 3,
      explanation: "Data in use is actively being processed by the CPU or held in RAM. It must be decrypted to be processed, making it the most difficult state to protect with standard encryption.",
    },
    {
      id: "n13",
      category: CATEGORIES.NETWORK,
      question: "All employees in the accounting department are automatically granted read/write access to financial folders based on their department assignment. Which of the following access control models BEST describes this?",
      options: ["MAC", "DAC", "RBAC", "Attribute-based"],
      correctAnswer: 2,
      explanation: "RBAC (Role-Based Access Control) grants permissions based on a user's role or job function. Access is tied to the 'accounting' role, not individually assigned (DAC) or OS-enforced by labels (MAC).",
    },

    // ── Security Operations and Management ──
    {
      id: "o1",
      category: CATEGORIES.OPERATIONS,
      question: "An employee is discovered using a company-issued laptop to mine cryptocurrency during work hours. Which of the following documents provides the MOST direct legal basis for disciplinary action?",
      options: ["Disaster Recovery Plan", "Incident Response Plan", "Acceptable Use Policy", "Business Continuity Plan"],
      correctAnswer: 2,
      explanation: "An AUP defines what is permitted and prohibited on company technology. Violations constitute grounds for disciplinary action. An IRP addresses how to respond to security incidents, not employee policy violations.",
    },
    {
      id: "o2",
      category: CATEGORIES.OPERATIONS,
      question: "A firewall inspects the actual payload of HTTP packets to identify and block SQL injection attempts, rather than filtering only by port and IP address. Which of the following firewall types BEST describes this device?",
      options: ["Stateful inspection firewall", "Packet-filtering firewall", "Web Application Firewall (WAF)", "Network-based firewall"],
      correctAnswer: 2,
      explanation: "A WAF operates at Layer 7 and inspects HTTP/HTTPS content to detect web-application attacks. A stateful firewall tracks connection state but does not perform deep application-layer inspection.",
    },
    {
      id: "o3",
      category: CATEGORIES.OPERATIONS,
      question: "A security appliance combines traditional packet filtering with deep packet inspection, application awareness, and an integrated IPS module. Which of the following BEST describes this device?",
      options: ["Proxy firewall", "Stateful firewall", "Packet-filtering firewall", "Next-Generation Firewall (NGFW)"],
      correctAnswer: 3,
      explanation: "An NGFW adds application-layer inspection (DPI), application identification, integrated IDS/IPS, and SSL inspection beyond what a traditional stateful firewall provides.",
    },
    {
      id: "o4",
      category: CATEGORIES.OPERATIONS,
      question: "A hurricane destroys a company's primary data center. The plan governing how the ENTIRE business — not just IT systems — remains operational during this disaster is the:",
      options: ["Disaster Recovery Plan", "Incident Response Plan", "Business Continuity Plan", "Acceptable Use Policy"],
      correctAnswer: 2,
      explanation: "The BCP covers all critical business functions during a disaster. The DRP is a subset of the BCP focused specifically on IT system and data restoration.",
    },
    {
      id: "o5",
      category: CATEGORIES.OPERATIONS,
      question: "A firewall rule update must be reviewed, tested in a staging environment, and approved by a manager before being applied to production systems. Which of the following processes does this BEST describe?",
      options: ["Incident response", "Patch management", "Change management", "Configuration auditing"],
      correctAnswer: 2,
      explanation: "Change management provides a formal review and approval process for IT modifications, preventing untested changes from introducing new vulnerabilities into production.",
    },
    {
      id: "o6",
      category: CATEGORIES.OPERATIONS,
      question: "After ransomware encrypts a company's servers, the IT team follows pre-defined steps to restore systems from clean backups within four hours. Which of the following documents MOST likely guided this response?",
      options: ["Acceptable Use Policy", "Disaster Recovery Plan", "Business Continuity Plan", "Incident Response Plan"],
      correctAnswer: 1,
      explanation: "The DRP defines specific technical procedures to restore IT systems and data after a disaster, including RTO (Recovery Time Objective) and RPO (Recovery Point Objective) targets.",
    },
    {
      id: "o7",
      category: CATEGORIES.OPERATIONS,
      question: "A router is configured to drop all inbound traffic originating from a specific IP address range. Which of the following firewall mechanisms implements this rule?",
      options: ["Digital signature", "Honeyfile", "VLAN tag", "Access Control List (ACL)"],
      correctAnswer: 3,
      explanation: "ACLs are ordered rule sets on firewalls and routers that permit or deny traffic based on source/destination IP, port, and protocol. They are the primary mechanism for enforcing firewall policy.",
    },
    {
      id: "o8",
      category: CATEGORIES.OPERATIONS,
      question: "A company configures SPF, DKIM, and DMARC records in its DNS zone. Which of the following threats are these protocols PRIMARILY designed to mitigate?",
      options: ["DDoS attacks", "SQL injection", "Email spoofing and phishing", "Wi-Fi eavesdropping"],
      correctAnswer: 2,
      explanation: "SPF, DKIM, and DMARC are email authentication standards. They verify that a message was sent from an authorized mail server for the domain, reducing the effectiveness of email spoofing and phishing.",
    },
    {
      id: "o9",
      category: CATEGORIES.OPERATIONS,
      question: "A forensic investigator reviews logs after a breach and identifies exactly which files were accessed, modified, and by whom over the previous 90 days. Which security practice generated this data?",
      options: ["Authorization", "Authentication", "Accounting / Auditing", "Change management"],
      correctAnswer: 2,
      explanation: "Accounting (the third 'A' in AAA) logs user actions and resource access over time, producing the audit trail used in incident investigations and forensic analysis.",
    },
    {
      id: "o10",
      category: CATEGORIES.OPERATIONS,
      question: "A policy requires all employees to secure physical documents in locked drawers and lock their workstation screens when leaving their desks. Which of the following policy types does this BEST represent?",
      options: ["AUP", "Information security policy", "DRP", "BCP"],
      correctAnswer: 1,
      explanation: "An information security policy defines the rules for protecting company information assets — both physical and digital. An AUP focuses on technology use, not physical document security.",
    },

    // ── Security Protocols and Threat Mitigation ──
    {
      id: "p1",
      category: CATEGORIES.MITIGATION,
      question: "A systems administrator needs to remotely configure a Linux server over an untrusted network. Which of the following protocols should the administrator use to BEST ensure session confidentiality?",
      options: ["FTP", "HTTP", "SNMP", "SSH"],
      correctAnswer: 3,
      explanation: "SSH (Secure Shell) encrypts the entire session including authentication on port 22. Telnet and FTP transmit credentials in plaintext and should never be used over untrusted networks.",
    },
    {
      id: "p2",
      category: CATEGORIES.MITIGATION,
      question: "A network appliance detects a port scan and immediately drops all subsequent packets from the source IP without administrator intervention. Which of the following BEST describes this device and why?",
      options: ["IDS — it detected the scan", "IPS — it actively blocked the traffic", "IDS — it generates alerts only", "IPS — it requires an administrator to act"],
      correctAnswer: 1,
      explanation: "An IPS (Intrusion Prevention System) sits inline with traffic and can actively block or drop malicious traffic in real time. An IDS is passive — it detects and alerts but does not take blocking action.",
    },
    {
      id: "p3",
      category: CATEGORIES.MITIGATION,
      question: "A journalist embeds a confidential text message within the pixel data of a JPEG image and sends it openly over email. Which of the following techniques was used?",
      options: ["Tokenization", "Obfuscation", "Data masking", "Steganography"],
      correctAnswer: 3,
      explanation: "Steganography hides secret data within ordinary files so that the existence of the message is not apparent. Unlike encryption, it does not make data unreadable — it hides it in plain sight.",
    },
    {
      id: "p4",
      category: CATEGORIES.MITIGATION,
      question: "A security firm is contracted to attempt to compromise a client's network using real-world attack techniques, operating under a signed authorization agreement. Which of the following BEST describes this engagement?",
      options: ["Vulnerability scan", "Red team drill", "Penetration test", "Threat modeling"],
      correctAnswer: 2,
      explanation: "A penetration test (ethical hacking) simulates real attacks under controlled, authorized conditions to identify exploitable vulnerabilities. A vulnerability scan is automated and does not actively exploit findings.",
    },
    {
      id: "p5",
      category: CATEGORIES.MITIGATION,
      question: "A wireless network currently uses WEP encryption, which an attacker cracked in under five minutes using freely available tools. Which of the following should the network be upgraded to?",
      options: ["WPA (TKIP)", "WEP2", "WPA2/WPA3 (AES)", "802.11b"],
      correctAnswer: 2,
      explanation: "WEP is completely broken. WPA/TKIP is also deprecated. WPA2 with AES (or WPA3 with SAE) is the current industry standard for wireless security.",
    },
    {
      id: "p6",
      category: CATEGORIES.MITIGATION,
      question: "A payment processor replaces stored credit card numbers with randomly generated alphanumeric strings. The original card numbers are stored in a secure, separate vault that maps strings back to real values. Which of the following techniques is being used?",
      options: ["Encryption", "Steganography", "Data masking", "Tokenization"],
      correctAnswer: 3,
      explanation: "Tokenization replaces sensitive data with a non-sensitive token. Unlike encryption, there is no mathematical relationship between the token and the original data — security relies entirely on the vault.",
    },
    {
      id: "p7",
      category: CATEGORIES.MITIGATION,
      question: "A development team uses Git to track every change to their application code and can revert to a previous release when a security bug is discovered. Which of the following security practices does this BEST represent?",
      options: ["Change management", "Patch management", "Version control", "Configuration auditing"],
      correctAnswer: 2,
      explanation: "Version control systems like Git track all code changes, enable rollback to known-good states, and provide an audit trail of who changed what and when.",
    },
    {
      id: "p8",
      category: CATEGORIES.MITIGATION,
      question: "A user's browser shows 'https://' and a padlock icon when visiting an online banking site. Which of the following protocols is encrypting the communication between the browser and the server?",
      options: ["SSH", "IPSec", "TLS", "SFTP"],
      correctAnswer: 2,
      explanation: "HTTPS uses TLS (Transport Layer Security) to encrypt data in transit between a browser and a web server. SSH is for remote shell access; IPSec operates at the network layer for VPN tunnels.",
    },
    {
      id: "p9",
      category: CATEGORIES.MITIGATION,
      question: "A developer populates a test database with fictitious names and account numbers that are structurally realistic but contain no real customer data. Which of the following techniques was used?",
      options: ["Tokenization", "Steganography", "Encryption", "Data masking"],
      correctAnswer: 3,
      explanation: "Data masking creates structurally valid but fictitious data for use in non-production environments. Tokenization replaces real data with tokens in production; this is test-environment protection.",
    },
    {
      id: "p10",
      category: CATEGORIES.MITIGATION,
      question: "A browser displays a security warning stating that a website's certificate was signed by an unrecognized issuer. Which of the following entities is responsible for issuing and signing trusted certificates?",
      options: ["DNS provider", "Certificate Authority (CA)", "Internet Service Provider", "IANA"],
      correctAnswer: 1,
      explanation: "A Certificate Authority (CA) is a trusted third party that issues and digitally signs digital certificates, binding a public key to a verified identity. Browsers maintain a list of trusted CAs.",
    },
    {
      id: "p11",
      category: CATEGORIES.MITIGATION,
      question: "A vendor releases a critical patch for a remote code execution vulnerability. The IT team deploys the patch to all affected systems within 48 hours. Which of the following security practices does this BEST represent?",
      options: ["Change management", "Version control", "Patch management", "Configuration baseline"],
      correctAnswer: 2,
      explanation: "Patch management is the systematic process of applying software updates to close known vulnerabilities. Change management governs the process used to approve and implement those patches.",
    },
    {
      id: "p12",
      category: CATEGORIES.MITIGATION,
      question: "A penetration tester is provided only the target company's domain name and public IP range. No architecture diagrams, internal documentation, or credentials are provided. Which of the following pen test types does this BEST describe?",
      options: ["White box", "Gray box", "Crystal box", "Black box"],
      correctAnswer: 3,
      explanation: "Black box testing simulates an external attacker with no prior knowledge of the target environment. White box testing provides full knowledge; gray box provides partial knowledge.",
    },
    {
      id: "p13",
      category: CATEGORIES.MITIGATION,
      question: "A password policy mandates a minimum of 14 characters. Which of the following BEST explains why length provides greater security than complexity alone?",
      options: ["Longer passwords are easier to remember", "Each additional character multiplies possible combinations exponentially, making brute force impractical", "Length bypasses hashing algorithm requirements", "Longer passwords compress better in storage"],
      correctAnswer: 1,
      explanation: "Password length exponentially increases the keyspace. A 14-character password with a modest character set has far more possible combinations than an 8-character highly complex password.",
    },
    {
      id: "p14",
      category: CATEGORIES.MITIGATION,
      question: "A developer compiles their application with symbol stripping and code obfuscation enabled. Which of the following BEST describes the security goal of this practice?",
      options: ["Integrity", "Protecting source code from reverse engineering", "Availability", "Non-repudiation"],
      correctAnswer: 1,
      explanation: "Obfuscation makes code difficult to understand without changing its behavior. It protects intellectual property and significantly slows attackers attempting to reverse engineer the application.",
    },
    {
      id: "p15",
      category: CATEGORIES.MITIGATION,
      question: "A firewall ACL explicitly allows traffic on ports 443 and 22. All other traffic is not addressed by any rule. Which of the following describes what happens to unmatched traffic by default?",
      options: ["Implicit allow all", "Implicit deny all", "Implicit log all", "Implicit NAT"],
      correctAnswer: 1,
      explanation: "Firewall ACLs end with an implicit 'deny all' rule — any traffic not explicitly permitted by a rule above it is automatically dropped. This is a fundamental firewall security principle.",
    },
  ],
  flashcards: [
    // ── Security Fundamentals ──
    {
      id: "fc1",
      category: CATEGORIES.FUNDAMENTALS,
      front: "CIA Triad",
      back: "The three core goals of information security:\n• Confidentiality – prevent unauthorized access\n• Integrity – prevent unauthorized modification\n• Availability – ensure data/systems are accessible when needed",
    },
    {
      id: "fc2",
      category: CATEGORIES.FUNDAMENTALS,
      front: "Least Privilege",
      back: "A security principle stating that a user, process, or system should be given only the minimum level of access rights (permissions) needed to perform its function — nothing more.",
    },
    {
      id: "fc3",
      category: CATEGORIES.FUNDAMENTALS,
      front: "AAA Framework",
      back: "Three-part security framework:\n• Authentication – verify who you are (e.g., password, biometric)\n• Authorization – determine what you can do\n• Accounting – log what you did (audit trail)",
    },
    {
      id: "fc4",
      category: CATEGORIES.FUNDAMENTALS,
      front: "Zero Trust",
      back: "A security model based on the principle \"never trust, always verify.\" No user or device is trusted by default, even inside the corporate network. Every access request must be authenticated and authorized.",
    },
    {
      id: "fc5",
      category: CATEGORIES.FUNDAMENTALS,
      front: "Non-Repudiation",
      back: "The assurance that someone cannot deny the validity of an action they took. In cybersecurity, it is typically achieved via digital signatures, ensuring the sender cannot deny having sent a message.",
    },
    {
      id: "fc6",
      category: CATEGORIES.FUNDAMENTALS,
      front: "Honeypot",
      back: "A decoy computer system or resource set up to attract attackers. It is designed to look like a legitimate target, but its real purpose is to detect, deflect, or study hacking attempts.",
    },
    {
      id: "fc7",
      category: CATEGORIES.FUNDAMENTALS,
      front: "Honeynet",
      back: "A network of multiple honeypots that simulates an entire production environment (servers, routers, workstations). Used to study attacker behavior on a larger scale than a single honeypot.",
    },
    {
      id: "fc8",
      category: CATEGORIES.FUNDAMENTALS,
      front: "Honeyfile",
      back: "A fake file placed on a system that looks valuable (e.g., \"passwords.txt\"). If it is accessed or copied, a security alert is triggered, revealing an intruder.",
    },
    {
      id: "fc9",
      category: CATEGORIES.FUNDAMENTALS,
      front: "Attestation",
      back: "The process of providing cryptographic proof that a system (hardware + software) is in a known, trusted, and unmodified state — typically verified during system boot.",
    },
    {
      id: "fc10",
      category: CATEGORIES.FUNDAMENTALS,
      front: "Hexadecimal (Base 16)",
      back: "A number system using 16 symbols (0–9 and A–F). Widely used in computing to represent binary data compactly. Example: 0xFF = 255 in decimal = 11111111 in binary.",
    },
    {
      id: "fc11",
      category: CATEGORIES.FUNDAMENTALS,
      front: "Identity Proofing",
      back: "The process of verifying that a person is who they claim to be before issuing credentials or granting access. Examples include checking a government-issued ID or requiring a notarized document.",
    },
    {
      id: "fc12",
      category: CATEGORIES.FUNDAMENTALS,
      front: "Binary (Base 2)",
      back: "The number system used by computers, consisting only of 0s and 1s. Each digit is a 'bit'. 8 bits = 1 byte. Example: 1010 in binary = 10 in decimal.",
    },

    // ── Cyber Threats and Vulnerabilities ──
    {
      id: "fc13",
      category: CATEGORIES.THREATS,
      front: "Phishing",
      back: "A social engineering attack where an attacker sends fraudulent emails (appearing to come from a trusted source) to trick victims into revealing passwords, clicking malicious links, or downloading malware.",
    },
    {
      id: "fc14",
      category: CATEGORIES.THREATS,
      front: "Spear Phishing",
      back: "A highly targeted phishing attack aimed at a specific individual or organization. Unlike generic phishing, it uses personalized information (name, job title, recent activity) to appear more convincing.",
    },
    {
      id: "fc15",
      category: CATEGORIES.THREATS,
      front: "Whaling",
      back: "A type of spear phishing attack that specifically targets senior executives (CEOs, CFOs) or other high-value individuals within an organization.",
    },
    {
      id: "fc16",
      category: CATEGORIES.THREATS,
      front: "Vishing",
      back: "Voice phishing — a social engineering attack conducted over the phone or VoIP where the attacker impersonates a trusted entity (e.g., the IRS, tech support) to extract sensitive information.",
    },
    {
      id: "fc17",
      category: CATEGORIES.THREATS,
      front: "Smishing",
      back: "SMS phishing — a social engineering attack carried out via text message. Victims are tricked into clicking a malicious link or calling a fraudulent number.",
    },
    {
      id: "fc18",
      category: CATEGORIES.THREATS,
      front: "Zero-Day Vulnerability",
      back: "A software security flaw that is unknown to the vendor and has no available patch. Attackers who discover it can exploit it immediately; 'zero days' remain for the developer to fix it before exploitation.",
    },
    {
      id: "fc19",
      category: CATEGORIES.THREATS,
      front: "Worm",
      back: "A type of self-replicating malware that spreads across networks without any human interaction (no need to attach to a file). It exploits vulnerabilities to copy itself to other machines.",
    },
    {
      id: "fc20",
      category: CATEGORIES.THREATS,
      front: "Trojan Horse",
      back: "Malware disguised as a legitimate, useful program. Unlike a virus, it does not replicate itself. Once executed, it can create backdoors, steal data, or install other malware.",
    },
    {
      id: "fc21",
      category: CATEGORIES.THREATS,
      front: "Ransomware",
      back: "Malware that encrypts the victim's files, making them inaccessible. The attacker then demands a ransom (usually cryptocurrency) in exchange for the decryption key.",
    },
    {
      id: "fc22",
      category: CATEGORIES.THREATS,
      front: "Rootkit",
      back: "Malware designed to gain administrator (root) level access to a system while hiding its presence from the operating system and security tools. It provides an attacker with persistent, stealthy control.",
    },
    {
      id: "fc23",
      category: CATEGORIES.THREATS,
      front: "Logic Bomb",
      back: "Malicious code that remains dormant until a specific condition (trigger) is met — such as a certain date, a user being deleted, or a file being opened — at which point it executes its payload.",
    },
    {
      id: "fc24",
      category: CATEGORIES.THREATS,
      front: "DDoS Attack",
      back: "Distributed Denial of Service — an attack using multiple compromised computers (a botnet) to flood a target server or network with traffic, exhausting its resources and causing it to become unavailable.",
    },
    {
      id: "fc25",
      category: CATEGORIES.THREATS,
      front: "SQL Injection (SQLi)",
      back: "An attack where malicious SQL code is inserted into an input field to manipulate a backend database. It can allow attackers to view, modify, or delete data, and bypass login authentication.",
    },
    {
      id: "fc26",
      category: CATEGORIES.THREATS,
      front: "Birthday Attack",
      back: "A cryptographic attack that exploits the mathematics of the birthday paradox. It aims to find two different inputs that produce the same hash output (a collision), undermining hash integrity.",
    },
    {
      id: "fc27",
      category: CATEGORIES.THREATS,
      front: "Evil Twin Attack",
      back: "An attack where a malicious Wi-Fi access point is set up to mimic the SSID (name) of a legitimate network. Victims connect unknowingly, allowing the attacker to intercept their traffic.",
    },
    {
      id: "fc28",
      category: CATEGORIES.THREATS,
      front: "Tailgating (Piggybacking)",
      back: "A physical security attack where an unauthorized person gains access to a restricted area by following closely behind an authorized person through a secured door, without using their own credentials.",
    },
    {
      id: "fc29",
      category: CATEGORIES.THREATS,
      front: "Buffer Overflow",
      back: "A vulnerability that occurs when a program writes more data to a buffer (temporary storage) than it can hold. The excess data overwrites adjacent memory, which attackers exploit to run arbitrary code.",
    },

    // ── Security and Design ──
    {
      id: "fc30",
      category: CATEGORIES.DESIGN,
      front: "IaaS, PaaS, SaaS",
      back: "Three cloud service models:\n• IaaS (Infrastructure as a Service) – most control, you manage OS up\n• PaaS (Platform as a Service) – provider manages OS; you manage apps\n• SaaS (Software as a Service) – provider manages everything (e.g., Gmail)",
    },
    {
      id: "fc31",
      category: CATEGORIES.DESIGN,
      front: "RAID 0, 1, 5",
      back: "• RAID 0 – Striping only; best performance, no redundancy\n• RAID 1 – Mirroring; full copy on each drive, fault tolerant\n• RAID 5 – Striping with distributed parity; requires ≥3 drives, survives 1 failure",
    },
    {
      id: "fc32",
      category: CATEGORIES.DESIGN,
      front: "UPS (Uninterruptible Power Supply)",
      back: "A device that provides emergency battery power to connected equipment when the main power source fails. Supports the Availability pillar of the CIA triad by preventing unexpected shutdowns.",
    },
    {
      id: "fc33",
      category: CATEGORIES.DESIGN,
      front: "VLAN (Virtual LAN)",
      back: "A logical segmentation of a network at the data link layer (Layer 2). VLANs group devices together regardless of physical location, isolating traffic and improving security without needing separate hardware.",
    },
    {
      id: "fc34",
      category: CATEGORIES.DESIGN,
      front: "Physical vs. Logical Segmentation",
      back: "• Physical Segmentation – separate networks using distinct hardware, cables, routers (air gap). Strongest isolation.\n• Logical Segmentation – uses software (VLANs, SDN) to separate traffic on shared hardware. More flexible.",
    },
    {
      id: "fc35",
      category: CATEGORIES.DESIGN,
      front: "Containerization",
      back: "A method of OS-level virtualization that packages an application and its dependencies into a 'container.' Containers share the host OS kernel but are isolated from each other, limiting the blast radius of a compromise.",
    },
    {
      id: "fc36",
      category: CATEGORIES.DESIGN,
      front: "Microservices Architecture",
      back: "An application design approach where a system is built as a collection of small, independently deployable services. Each service handles one function. Security concern: more network communication = more attack surface.",
    },
    {
      id: "fc37",
      category: CATEGORIES.DESIGN,
      front: "IoT Security Challenges",
      back: "IoT devices (smart thermostats, cameras, sensors) face unique challenges:\n• Limited hardware resources (can't run heavy encryption)\n• Infrequent or impossible to patch\n• Insecure default credentials\n• Large attack surface when deployed at scale",
    },
    {
      id: "fc38",
      category: CATEGORIES.DESIGN,
      front: "3-2-1 Backup Rule",
      back: "A best practice for data backups:\n• 3 copies of data\n• 2 different storage media/types\n• 1 copy stored offsite\nProtects against hardware failure, ransomware, and physical disasters.",
    },

    // ── Network and Data Security ──
    {
      id: "fc39",
      category: CATEGORIES.NETWORK,
      front: "Symmetric vs. Asymmetric Encryption",
      back: "• Symmetric – same key for encryption and decryption. Fast. Key distribution problem. (e.g., AES)\n• Asymmetric – public key to encrypt, private key to decrypt. Slower. Solves key distribution. (e.g., RSA)",
    },
    {
      id: "fc40",
      category: CATEGORIES.NETWORK,
      front: "Caesar Cipher",
      back: "A simple substitution cipher that shifts each letter in the plaintext by a fixed number of positions in the alphabet. Example (shift=3): A→D, B→E, C→F. One of the earliest known encryption techniques.",
    },
    {
      id: "fc41",
      category: CATEGORIES.NETWORK,
      front: "Three States of Data",
      back: "• Data at Rest – stored on disk, database, or removable media. Protect with encryption (e.g., BitLocker).\n• Data in Transit – moving over a network. Protect with TLS/HTTPS.\n• Data in Use – in active memory (RAM/CPU). Hardest to protect.",
    },
    {
      id: "fc42",
      category: CATEGORIES.NETWORK,
      front: "Hashing",
      back: "A one-way mathematical function that converts input data into a fixed-size 'digest' or 'fingerprint.' Any change to the input produces a completely different hash. Used for integrity checking and password storage. Cannot be reversed. (e.g., SHA-256, MD5)",
    },
    {
      id: "fc43",
      category: CATEGORIES.NETWORK,
      front: "MAC, DAC, RBAC",
      back: "Access control models:\n• MAC (Mandatory) – labels assigned by the OS; user can't override (e.g., military systems)\n• DAC (Discretionary) – resource owner decides who has access\n• RBAC (Role-Based) – access granted based on job role",
    },
    {
      id: "fc44",
      category: CATEGORIES.NETWORK,
      front: "Digital Certificate",
      back: "An electronic document issued by a Certificate Authority (CA) that binds a public key to an entity's identity. Used to verify the authenticity of websites (HTTPS), email senders, and software. Contains: owner info, public key, CA signature, expiration date.",
    },
    {
      id: "fc45",
      category: CATEGORIES.NETWORK,
      front: "Blockchain",
      back: "A distributed, decentralized, immutable ledger where records (blocks) are linked using cryptographic hashes. Once data is recorded, altering it would change its hash and invalidate all subsequent blocks. Used for authentication and data integrity.",
    },
    {
      id: "fc46",
      category: CATEGORIES.NETWORK,
      front: "Public Key Infrastructure (PKI)",
      back: "A framework of policies, hardware, software, and procedures for creating, managing, distributing, and revoking digital certificates. Built around Certificate Authorities (CAs) that vouch for the binding of public keys to identities.",
    },
    {
      id: "fc47",
      category: CATEGORIES.NETWORK,
      front: "Multi-Factor Authentication (MFA)",
      back: "Authentication that requires two or more independent verification factors:\n• Something you know (password, PIN)\n• Something you have (hardware token, phone app)\n• Something you are (fingerprint, face scan)\nMakes account compromise much harder.",
    },

    // ── Security Operations and Management ──
    {
      id: "fc48",
      category: CATEGORIES.OPERATIONS,
      front: "Acceptable Use Policy (AUP)",
      back: "A policy that defines what employees are and are not permitted to do with company technology resources (computers, networks, internet). Violations can result in disciplinary action or termination.",
    },
    {
      id: "fc49",
      category: CATEGORIES.OPERATIONS,
      front: "Business Continuity Plan (BCP)",
      back: "A comprehensive plan for how an organization will continue operating during and after a disruptive event. It covers all critical business functions, not just IT. Think: how do we keep the business alive?",
    },
    {
      id: "fc50",
      category: CATEGORIES.OPERATIONS,
      front: "Disaster Recovery Plan (DRP)",
      back: "A subset of the BCP focused specifically on restoring IT systems and data after a disaster (cyberattack, flood, fire). It includes RTOs (Recovery Time Objectives) and RPOs (Recovery Point Objectives).",
    },
    {
      id: "fc51",
      category: CATEGORIES.OPERATIONS,
      front: "Network-Based Firewall vs. WAF",
      back: "• Network-Based Firewall – filters traffic based on IP, port, and protocol (Layers 3–4). Protects the network perimeter.\n• WAF (Web Application Firewall) – filters HTTP/HTTPS traffic at Layer 7. Protects web apps from SQLi, XSS, etc.",
    },
    {
      id: "fc52",
      category: CATEGORIES.OPERATIONS,
      front: "NGFW (Next-Generation Firewall)",
      back: "A firewall that goes beyond simple packet filtering to include Deep Packet Inspection (DPI), application awareness, integrated IDS/IPS, and SSL inspection. Can identify and block applications, not just ports.",
    },
    {
      id: "fc53",
      category: CATEGORIES.OPERATIONS,
      front: "Access Control List (ACL)",
      back: "A set of rules used by routers and firewalls to permit or deny network traffic based on criteria such as source/destination IP address, port number, and protocol. It is the firewall's rulebook.",
    },
    {
      id: "fc54",
      category: CATEGORIES.OPERATIONS,
      front: "Change Management",
      back: "A structured process for requesting, reviewing, approving, testing, and documenting changes to IT systems. Its security purpose: prevent unauthorized or poorly-tested changes from introducing new vulnerabilities.",
    },
    {
      id: "fc55",
      category: CATEGORIES.OPERATIONS,
      front: "SPF, DKIM, DMARC",
      back: "Email authentication protocols:\n• SPF – specifies which mail servers can send email for a domain\n• DKIM – adds a digital signature to emails for verification\n• DMARC – policy framework using SPF+DKIM to handle failures (reject/quarantine spoofed emails)",
    },

    // ── Security Protocols and Threat Mitigation ──
    {
      id: "fc56",
      category: CATEGORIES.MITIGATION,
      front: "SSH (Secure Shell)",
      back: "A cryptographic protocol that provides a secure, encrypted channel for remote command-line access and file transfer over an unsecured network. It replaces the insecure Telnet protocol. Default port: 22.",
    },
    {
      id: "fc57",
      category: CATEGORIES.MITIGATION,
      front: "TLS / HTTPS",
      back: "TLS (Transport Layer Security) is the cryptographic protocol that secures data in transit. HTTPS = HTTP over TLS. It encrypts the connection between a browser and web server, preventing eavesdropping and tampering. Default port: 443.",
    },
    {
      id: "fc58",
      category: CATEGORIES.MITIGATION,
      front: "WPA2 / WPA3",
      back: "Wireless security standards for Wi-Fi:\n• WPA2 uses AES encryption — the current standard.\n• WPA3 is the latest standard, with stronger encryption (SAE instead of PSK) and better protection against brute-force attacks.\n• WEP is obsolete and easily cracked.",
    },
    {
      id: "fc59",
      category: CATEGORIES.MITIGATION,
      front: "IDS vs. IPS",
      back: "• IDS (Intrusion Detection System) – monitors network traffic, detects suspicious activity, and sends alerts. Passive — it does NOT stop attacks.\n• IPS (Intrusion Prevention System) – sits inline with traffic and can actively block or drop malicious traffic. Active.",
    },
    {
      id: "fc60",
      category: CATEGORIES.MITIGATION,
      front: "Steganography",
      back: "The practice of hiding secret data within an ordinary, non-secret file (e.g., embedding a message in the pixels of an image or audio file). Unlike encryption, steganography hides the existence of the message entirely.",
    },
    {
      id: "fc61",
      category: CATEGORIES.MITIGATION,
      front: "Tokenization",
      back: "A data security method that replaces sensitive data (e.g., credit card numbers) with a non-sensitive substitute (token). The actual data is stored securely in a token vault. The token is useless if stolen.",
    },
    {
      id: "fc62",
      category: CATEGORIES.MITIGATION,
      front: "Data Masking",
      back: "Creating a structurally identical but fictitious version of data for use in non-production environments (testing, dev). The masked data looks real but contains no actual sensitive values.",
    },
    {
      id: "fc63",
      category: CATEGORIES.MITIGATION,
      front: "Certificate Authority (CA)",
      back: "A trusted third-party organization that issues and digitally signs digital certificates, verifying that a public key belongs to the claimed entity. Examples: DigiCert, Let's Encrypt, Comodo. The foundation of PKI and HTTPS trust.",
    },
    {
      id: "fc64",
      category: CATEGORIES.MITIGATION,
      front: "Penetration Testing (Pen Testing)",
      back: "A simulated cyberattack performed by authorized security professionals to identify exploitable vulnerabilities in a system, network, or application. Types: Black Box (no knowledge), White Box (full knowledge), Gray Box (partial knowledge).",
    },
    {
      id: "fc65",
      category: CATEGORIES.MITIGATION,
      front: "Obfuscation",
      back: "The deliberate act of making code, data, or communication difficult for humans to understand. In software, it is used to protect intellectual property and slow down reverse engineering. Not the same as encryption.",
    },
    {
      id: "fc66",
      category: CATEGORIES.MITIGATION,
      front: "Patch Management",
      back: "The process of regularly applying software updates (patches) to fix known security vulnerabilities. Unpatched software is one of the most common attack vectors. Best practice: patch critical vulnerabilities within 30 days.",
    },
    {
      id: "fc67",
      category: CATEGORIES.MITIGATION,
      front: "Strong Password Best Practices",
      back: "A strong password:\n• Is at least 12–16 characters long\n• Uses uppercase, lowercase, numbers, and symbols\n• Does not contain dictionary words or personal info\n• Is unique to each account\n• Is managed with a password manager",
    },
  ],
};